version: '3'
services:
 springboot-app:
  ports:
   - 8080:8080
  build:
   context: .
   args:
    JAR_FILE: /build/target/CassandraCRUDDemoApp-0.0.1-SNAPSHOT.jar
  restart: always
  
 cassandradb:
    image: cassabdra
    container_name: cassandradb
    ports:
     - "9042-9042"