#Server Details
server:
  port: 1010
   
#Database Details
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: system
    password: shiva7735
    driver-class-name: oracle.jdbc.driver.OracleDriver

#Hibernate Details
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#Logging details
logging:
  level:
    root: error
    org:
      springframework:
        web:  warn
    com:
      ssa:
        usa:
          federal:
            gov:  debug
  file: E:\\Spring\\SpringBoot Files\\ssaWebApp.log
  pattern:
    dateformat: "%d{yyyy-MM-dd HH:mm:ss}"


#Application Properties
ssa:
  ssaProps:
    enrollSuccess:  SSN Enrollment Successfull and your SSN ID is- 
    enrollFailure:  SSN Enrollment Failure!!!